server:
  port: ${PORT:8080}

word-online:
  jwt:
    path: ${JWT_FILE_PATH}

spring:
  application:
    name: word-online-admin
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    user:
      name: ${APPLICATION_USER}
      password: ${APPLICATION_PW}